version: '2'

services:
  proxy:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - 9000:9000
    environment:
      PRETTY: 'true'
      TARGET: http://hello:3000
      # OUTPUT: tcp:tcp:3001
      # OUTPUT: stderr
      # OUTPUT: file:/tmp/test-:1:3
      RES_DECODE_JSON: 'true'
  
  hello:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - 3000:3000
    command: node test/hello-service.js

  tcp:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - 3001:3001
    command: node test/tcp-service.js
  
  ab:
    image: russmckendrick/ab